### ISSUE TITLE
Move generic util functions, classes from Aria and Spot to 3rd common package

### ISSUE THREAD

**Issue by zephirefaith** [facebookresearch/spot-sim2real#124]
This file had some functions such as _rotate_img(), _rectify_image() which are also repeated in aria_live_streamer.py. At some point in the future, we may want to move such functions in some utils file? Similarly, if I am not mistaken, the parse_camera_stream() function in aria_streamer basically does what process_frame() function in aria_live_streamer does but over the entire stream of frames. So perhaps this function can also be refactored into a "utility" to reduce code duplication.

_Originally posted by @rutadesai in https://github.com/facebookresearch/spot-sim2real/pull/110#discussion_r1449397524_

**Comment by KavitShah1998** [comment]
This issue will also resolve issue - https://github.com/facebookresearch/spot-sim2real/issues/117

**Comment by KavitShah1998** [comment]
This issue will also resolve issue - https://github.com/facebookresearch/spot-sim2real/issues/112
