### ISSUE TITLE
Move get_spot_a_tform_b to main Spot class and replace all get_ABC_T_XYZ calls with this generix function

### ISSUE THREAD

**Issue by zephirefaith** [facebookresearch/spot-sim2real#83]

**Comment by KavitShah1998** [comment]
Thank you @zephirefaith for making this issue. It would be easier to track it this way.

Will take this as next task

**Comment by KavitShah1998** [comment]
This issue will be addressed as a part of https://github.com/facebookresearch/spot-sim2real/issues/90
